import type { ChapterProgress } from '../types';

export const jeeMasterSyllabus: ChapterProgress[] = [
  // ==========================================
  // ⚛️ PHYSICS (40 Core Topics + Advanced)
  // ==========================================

  // --- 1. Mechanics (Class 11) ---
  {
    id: 'phy-1',
    name: 'Units, Dimensions & Measurement Errors',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Mastered',
    completionPercentage: 95,
    theoryCompleted: true,
    pyqsSolved: 65,
    totalPyqs: 70,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-2',
    name: 'Kinematics 1D & 2D (Projectile & Relative Motion)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Mastered',
    completionPercentage: 90,
    theoryCompleted: true,
    pyqsSolved: 85,
    totalPyqs: 90,
    keyFormulaeCount: 16,
  },
  {
    id: 'phy-3',
    name: 'Laws of Motion & Pseudo Forces',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 68,
    theoryCompleted: true,
    pyqsSolved: 48,
    totalPyqs: 75,
    keyFormulaeCount: 18,
  },
  {
    id: 'phy-4',
    name: 'Friction on Inclined Planes & Block Systems',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 60,
    theoryCompleted: true,
    pyqsSolved: 35,
    totalPyqs: 60,
    keyFormulaeCount: 14,
  },
  {
    id: 'phy-5',
    name: 'Circular Motion & Banking of Roads',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'In Progress',
    completionPercentage: 55,
    theoryCompleted: true,
    pyqsSolved: 28,
    totalPyqs: 55,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-6',
    name: 'Work, Power & Energy (Work-Energy Theorem)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 50,
    theoryCompleted: true,
    pyqsSolved: 28,
    totalPyqs: 65,
    keyFormulaeCount: 15,
  },
  {
    id: 'phy-7',
    name: 'Center of Mass & Linear Momentum',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 42,
    theoryCompleted: false,
    pyqsSolved: 20,
    totalPyqs: 60,
    keyFormulaeCount: 14,
  },
  {
    id: 'phy-8',
    name: 'Collisions (Elastic & Inelastic in 1D/2D)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 40,
    theoryCompleted: false,
    pyqsSolved: 18,
    totalPyqs: 50,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-9',
    name: 'Rotational Motion & Rigid Body Dynamics',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 15,
    theoryCompleted: false,
    pyqsSolved: 8,
    totalPyqs: 110,
    keyFormulaeCount: 24,
  },
  {
    id: 'phy-10',
    name: 'Gravitation & Kepler Planetary Laws',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 55,
    keyFormulaeCount: 14,
  },
  {
    id: 'phy-11',
    name: 'Properties of Matter & Elasticity (Youngs Modulus)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 45,
    keyFormulaeCount: 10,
  },
  {
    id: 'phy-12',
    name: 'Fluid Mechanics & Surface Tension (Bernoulli Theorem)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 20,
  },
  {
    id: 'phy-13',
    name: 'Simple Harmonic Motion (SHM & Oscillations)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 18,
  },
  {
    id: 'phy-14',
    name: 'Waves & Sound (Doppler Effect & Standing Waves)',
    subject: 'Physics',
    category: 'Mechanics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 16,
  },

  // --- 2. Thermal Physics & Thermodynamics ---
  {
    id: 'phy-15',
    name: 'Kinetic Theory of Gases (KTG)',
    subject: 'Physics',
    category: 'Thermodynamics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 40,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-16',
    name: 'Thermal Expansion & Calorimetry',
    subject: 'Physics',
    category: 'Thermodynamics',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 35,
    keyFormulaeCount: 10,
  },
  {
    id: 'phy-17',
    name: 'Heat Transfer (Conduction, Convection & Radiation)',
    subject: 'Physics',
    category: 'Thermodynamics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 60,
    keyFormulaeCount: 15,
  },
  {
    id: 'phy-18',
    name: 'Thermodynamics Laws & Carnot Cycles',
    subject: 'Physics',
    category: 'Thermodynamics',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 85,
    keyFormulaeCount: 18,
  },

  // --- 3. Electricity & Magnetism (Class 12) ---
  {
    id: 'phy-19',
    name: 'Electrostatics & Gauss Law',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 95,
    keyFormulaeCount: 22,
  },
  {
    id: 'phy-20',
    name: 'Capacitors & Dielectrics',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 16,
  },
  {
    id: 'phy-21',
    name: 'Current Electricity & Kirchhoff Laws',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 85,
    keyFormulaeCount: 19,
  },
  {
    id: 'phy-22',
    name: 'Moving Charges & Magnetic Effects of Current',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 20,
  },
  {
    id: 'phy-23',
    name: 'Magnetism & Matter (Earth Magnetism)',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 40,
    keyFormulaeCount: 10,
  },
  {
    id: 'phy-24',
    name: 'Electromagnetic Induction (EMI & Faraday Laws)',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 18,
  },
  {
    id: 'phy-25',
    name: 'Alternating Current (AC & LCR Resonance)',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 60,
    keyFormulaeCount: 15,
  },
  {
    id: 'phy-26',
    name: 'Electromagnetic Waves (EM Waves)',
    subject: 'Physics',
    category: 'Electricity & Magnetism',
    classLevel: 'Class 12',
    weightage: 'Low',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 30,
    keyFormulaeCount: 8,
  },

  // --- 4. Optics ---
  {
    id: 'phy-27',
    name: 'Ray Optics & Optical Instruments (Lenses & Mirrors)',
    subject: 'Physics',
    category: 'Optics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 90,
    keyFormulaeCount: 22,
  },
  {
    id: 'phy-28',
    name: 'Wave Optics (Youngs Double Slit & Diffraction)',
    subject: 'Physics',
    category: 'Optics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 16,
  },

  // --- 5. Modern Physics ---
  {
    id: 'phy-29',
    name: 'Dual Nature of Matter & Photoelectric Effect',
    subject: 'Physics',
    category: 'Modern Physics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 60,
    keyFormulaeCount: 14,
  },
  {
    id: 'phy-30',
    name: 'Atoms & Bohr Model Spectral Lines',
    subject: 'Physics',
    category: 'Modern Physics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 55,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-31',
    name: 'Nuclei & Radioactivity (Binding Energy)',
    subject: 'Physics',
    category: 'Modern Physics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 50,
    keyFormulaeCount: 12,
  },
  {
    id: 'phy-32',
    name: 'Semiconductor Electronics & Logic Gates',
    subject: 'Physics',
    category: 'Modern Physics',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 15,
  },
  {
    id: 'phy-33',
    name: 'Experimental Physics & Error Analysis',
    subject: 'Physics',
    category: 'Modern Physics',
    classLevel: 'Class 12',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 35,
    keyFormulaeCount: 10,
  },


  // ==========================================
  // 🧪 CHEMISTRY (50 Core Topics)
  // ==========================================

  // --- Physical Chemistry ---
  {
    id: 'chem-1',
    name: 'Some Basic Concepts of Chemistry (Mole Concept)',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'In Progress',
    completionPercentage: 75,
    theoryCompleted: true,
    pyqsSolved: 38,
    totalPyqs: 50,
    keyFormulaeCount: 12,
  },
  {
    id: 'chem-2',
    name: 'Atomic Structure & Quantum Numbers',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Mastered',
    completionPercentage: 90,
    theoryCompleted: true,
    pyqsSolved: 62,
    totalPyqs: 65,
    keyFormulaeCount: 16,
  },
  {
    id: 'chem-3',
    name: 'States of Matter (Gaseous State & Real Gases)',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 45,
    keyFormulaeCount: 14,
  },
  {
    id: 'chem-4',
    name: 'Chemical Thermodynamics & Thermochemistry',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 35,
    theoryCompleted: false,
    pyqsSolved: 15,
    totalPyqs: 70,
    keyFormulaeCount: 20,
  },
  {
    id: 'chem-5',
    name: 'Chemical Equilibrium & Le Chatelier Principle',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 15,
    theoryCompleted: false,
    pyqsSolved: 8,
    totalPyqs: 55,
    keyFormulaeCount: 14,
  },
  {
    id: 'chem-6',
    name: 'Ionic Equilibrium (pH & Buffer Solutions)',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 22,
  },
  {
    id: 'chem-7',
    name: 'Redox Reactions & Oxidation Numbers',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 40,
    keyFormulaeCount: 10,
  },
  {
    id: 'chem-8',
    name: 'Electrochemistry & Nernst Equation',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 20,
  },
  {
    id: 'chem-9',
    name: 'Chemical Kinetics & Rate Laws',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 18,
  },
  {
    id: 'chem-10',
    name: 'Solutions & Colligative Properties',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 16,
  },
  {
    id: 'chem-11',
    name: 'Solid State & Crystal Lattices',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 45,
    keyFormulaeCount: 12,
  },
  {
    id: 'chem-12',
    name: 'Surface Chemistry & Colloids',
    subject: 'Chemistry',
    category: 'Physical Chemistry',
    classLevel: 'Class 12',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 35,
    keyFormulaeCount: 8,
  },

  // --- Inorganic Chemistry ---
  {
    id: 'chem-13',
    name: 'Periodic Table & Periodicity in Properties',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Mastered',
    completionPercentage: 88,
    theoryCompleted: true,
    pyqsSolved: 50,
    totalPyqs: 55,
    keyFormulaeCount: 10,
  },
  {
    id: 'chem-14',
    name: 'Chemical Bonding & Molecular Structure (VSEPR & MOT)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 58,
    theoryCompleted: true,
    pyqsSolved: 35,
    totalPyqs: 80,
    keyFormulaeCount: 18,
  },
  {
    id: 'chem-15',
    name: 'Hydrogen & s-Block Elements (Alkali & Alkaline Earth Metals)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 45,
    keyFormulaeCount: 10,
  },
  {
    id: 'chem-16',
    name: 'p-Block Elements (Group 13 & 14 Boron & Carbon Family)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 55,
    keyFormulaeCount: 12,
  },
  {
    id: 'chem-17',
    name: 'p-Block Elements (Group 15 to 18 Nitrogen, Oxygen, Halogens)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 85,
    keyFormulaeCount: 16,
  },
  {
    id: 'chem-18',
    name: 'd-Block and f-Block Elements (Transition Metals)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 14,
  },
  {
    id: 'chem-19',
    name: 'Coordination Compounds & Crystal Field Theory (CFT)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 95,
    keyFormulaeCount: 20,
  },
  {
    id: 'chem-20',
    name: 'Metallurgy & Extraction of Metals',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightage: 'Medium',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 40,
    keyFormulaeCount: 8,
  },
  {
    id: 'chem-21',
    name: 'Qualitative Salt Analysis (Cations & Anions)',
    subject: 'Chemistry',
    category: 'Inorganic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 50,
    keyFormulaeCount: 15,
  },

  // --- Organic Chemistry ---
  {
    id: 'chem-22',
    name: 'General Organic Chemistry (GOC — Resonance & Inductive Effect)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 45,
    theoryCompleted: true,
    pyqsSolved: 30,
    totalPyqs: 105,
    keyFormulaeCount: 25,
  },
  {
    id: 'chem-23',
    name: 'Isomerism (Structural & Stereoisomerism R/S, E/Z)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 16,
  },
  {
    id: 'chem-24',
    name: 'Hydrocarbons (Alkanes, Alkenes, Alkynes & Aromaticity)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 90,
    keyFormulaeCount: 22,
  },
  {
    id: 'chem-25',
    name: 'Haloalkanes & Haloarenes (SN1 & SN2 Mechanisms)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 18,
  },
  {
    id: 'chem-26',
    name: 'Alcohols, Phenols & Ethers',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 85,
    keyFormulaeCount: 20,
  },
  {
    id: 'chem-27',
    name: 'Aldehydes & Ketones (Nucleophilic Addition & Aldol)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 100,
    keyFormulaeCount: 24,
  },
  {
    id: 'chem-28',
    name: 'Carboxylic Acids & Acid Derivatives',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 16,
  },
  {
    id: 'chem-29',
    name: 'Amines & Diazonium Salts',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 18,
  },
  {
    id: 'chem-30',
    name: 'Biomolecules (Carbohydrates, Amino Acids & DNA)',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 50,
    keyFormulaeCount: 12,
  },
  {
    id: 'chem-31',
    name: 'Practical Organic Chemistry & Named Reactions',
    subject: 'Chemistry',
    category: 'Organic Chemistry',
    classLevel: 'Class 12',
    weightage: 'High',
    isAdvancedOnly: true,
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 60,
    keyFormulaeCount: 20,
  },


  // ==========================================
  // 📘 MATHEMATICS (45 Core Topics)
  // ==========================================

  // --- 1. Sets, Relations & Functions ---
  {
    id: 'math-1',
    name: 'Sets & Set Operations',
    subject: 'Mathematics',
    category: 'Sets, Relations & Functions',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Mastered',
    completionPercentage: 95,
    theoryCompleted: true,
    pyqsSolved: 40,
    totalPyqs: 42,
    keyFormulaeCount: 8,
  },
  {
    id: 'math-2',
    name: 'Relations & Equivalence Classes',
    subject: 'Mathematics',
    category: 'Sets, Relations & Functions',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'Mastered',
    completionPercentage: 90,
    theoryCompleted: true,
    pyqsSolved: 35,
    totalPyqs: 38,
    keyFormulaeCount: 10,
  },
  {
    id: 'math-3',
    name: 'Functions (Domain, Range & Types of Functions)',
    subject: 'Mathematics',
    category: 'Sets, Relations & Functions',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 70,
    theoryCompleted: true,
    pyqsSolved: 50,
    totalPyqs: 75,
    keyFormulaeCount: 16,
  },
  {
    id: 'math-4',
    name: 'Composite & Inverse Functions',
    subject: 'Mathematics',
    category: 'Sets, Relations & Functions',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 55,
    keyFormulaeCount: 12,
  },

  // --- 2. Trigonometry ---
  {
    id: 'math-5',
    name: 'Trigonometric Ratios & Identities',
    subject: 'Mathematics',
    category: 'Trigonometry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 60,
    theoryCompleted: true,
    pyqsSolved: 35,
    totalPyqs: 60,
    keyFormulaeCount: 22,
  },
  {
    id: 'math-6',
    name: 'Trigonometric Equations & General Solutions',
    subject: 'Mathematics',
    category: 'Trigonometry',
    classLevel: 'Class 11',
    weightage: 'Medium',
    status: 'In Progress',
    completionPercentage: 45,
    theoryCompleted: false,
    pyqsSolved: 20,
    totalPyqs: 50,
    keyFormulaeCount: 14,
  },
  {
    id: 'math-7',
    name: 'Inverse Trigonometric Functions (ITF)',
    subject: 'Mathematics',
    category: 'Trigonometry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 18,
  },

  // --- 3. Algebra ---
  {
    id: 'math-8',
    name: 'Logarithms, Modulus & Inequalities',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Mastered',
    completionPercentage: 92,
    theoryCompleted: true,
    pyqsSolved: 55,
    totalPyqs: 60,
    keyFormulaeCount: 15,
  },
  {
    id: 'math-9',
    name: 'Quadratic Equations & Location of Roots',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 78,
    theoryCompleted: true,
    pyqsSolved: 55,
    totalPyqs: 70,
    keyFormulaeCount: 14,
  },
  {
    id: 'math-10',
    name: 'Sequences & Series (AP, GP, AGP & Special Series)',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Mastered',
    completionPercentage: 92,
    theoryCompleted: true,
    pyqsSolved: 68,
    totalPyqs: 72,
    keyFormulaeCount: 16,
  },
  {
    id: 'math-11',
    name: 'Complex Numbers & De Moivre Theorem',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 15,
    theoryCompleted: false,
    pyqsSolved: 8,
    totalPyqs: 85,
    keyFormulaeCount: 20,
  },
  {
    id: 'math-12',
    name: 'Binomial Theorem & Properties of Coefficients',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 14,
  },
  {
    id: 'math-13',
    name: 'Permutation & Combination (P&C)',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 18,
  },
  {
    id: 'math-14',
    name: 'Probability & Bayes Theorem',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 90,
    keyFormulaeCount: 20,
  },
  {
    id: 'math-15',
    name: 'Matrices & Determinants (System of Equations)',
    subject: 'Mathematics',
    category: 'Algebra',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 90,
    keyFormulaeCount: 16,
  },

  // --- 4. Coordinate Geometry ---
  {
    id: 'math-16',
    name: 'Straight Line & Pair of Straight Lines',
    subject: 'Mathematics',
    category: 'Coordinate Geometry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'In Progress',
    completionPercentage: 50,
    theoryCompleted: true,
    pyqsSolved: 30,
    totalPyqs: 65,
    keyFormulaeCount: 18,
  },
  {
    id: 'math-17',
    name: 'Circle & System of Circles',
    subject: 'Mathematics',
    category: 'Coordinate Geometry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 20,
  },
  {
    id: 'math-18',
    name: 'Parabola (Standard Equations & Tangents)',
    subject: 'Mathematics',
    category: 'Coordinate Geometry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 18,
  },
  {
    id: 'math-19',
    name: 'Ellipse & Hyperbola (Conic Sections)',
    subject: 'Mathematics',
    category: 'Coordinate Geometry',
    classLevel: 'Class 11',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 22,
  },

  // --- 5. Vector Algebra & 3D Geometry ---
  {
    id: 'math-20',
    name: 'Vector Algebra (Dot, Cross & Triple Product)',
    subject: 'Mathematics',
    category: 'Vector & 3D Geometry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 85,
    keyFormulaeCount: 20,
  },
  {
    id: 'math-21',
    name: '3D Geometry (Lines, Planes & Shortest Distance)',
    subject: 'Mathematics',
    category: 'Vector & 3D Geometry',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 95,
    keyFormulaeCount: 24,
  },

  // --- 6. Calculus ---
  {
    id: 'math-22',
    name: 'Limits & L\'Hopital Rule',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 65,
    keyFormulaeCount: 15,
  },
  {
    id: 'math-23',
    name: 'Continuity & Differentiability',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 70,
    keyFormulaeCount: 16,
  },
  {
    id: 'math-24',
    name: 'Differentiation & Chain Rule',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 50,
    keyFormulaeCount: 18,
  },
  {
    id: 'math-25',
    name: 'Applications of Derivatives (Maxima & Minima, Tangents)',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 90,
    keyFormulaeCount: 22,
  },
  {
    id: 'math-26',
    name: 'Indefinite Integration',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 80,
    keyFormulaeCount: 25,
  },
  {
    id: 'math-27',
    name: 'Definite Integration & Kings Property',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 95,
    keyFormulaeCount: 20,
  },
  {
    id: 'math-28',
    name: 'Area Under Curve (AUC)',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 60,
    keyFormulaeCount: 12,
  },
  {
    id: 'math-29',
    name: 'Differential Equations (Variable Separable & Linear DE)',
    subject: 'Mathematics',
    category: 'Calculus',
    classLevel: 'Class 12',
    weightage: 'High',
    status: 'Not Started',
    completionPercentage: 0,
    theoryCompleted: false,
    pyqsSolved: 0,
    totalPyqs: 75,
    keyFormulaeCount: 16,
  },
];
